# ============================================================
# API ? API ?????????
# ============================================================
CreateUserRequest=CreateUserResponse:username=username,password=password,role=role
DepositRequest=DepositResponse:id=id,balance=balance
TransferRequest=TransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
UpdateCustomerProfileRequest=UpdateCustomerProfileResponse:name=customer.name

# ============================================================
# API ? DB ?????????
# ============================================================
AccountDTO=AccountDao:id=id,accountNumber=accountNumber,balance=balance,customerId=customerId
TransactionDTO=TransactionDao:id=id,amount=amount,type=type,timestamp=timestamp,accountId=accountId,relatedAccountId=relatedAccountId

# ============================================================
# DB ? DB ?????????
# ============================================================
AccountDao=AccountDaoV2:id=id,accountNumber=accountNumber,balance=balance
TransactionDao=TransactionDaoV2:id=id,amount=amount,type=type